In [1]:
import numpy as np

In [4]:
# Ismlar
names = np.array(['Islom', 'Siroj', 'Shaxboz', 'Islom' ,'Ozodbek', 'Suhrob', 'Dilshod'])
names

array(['Islom', 'Siroj', 'Shaxboz', 'Islom', 'Ozodbek', 'Suhrob',
       'Dilshod'], dtype='<U7')

In [5]:
# data
data = np.random.randn(7, 5) # 7 ta insonga tog'ri keladigan ma'lumotlar (7x5 ulchamli)
data

array([[-0.91146962, -0.76622313,  1.6146796 ,  0.04663843, -0.09685263],
       [-1.05639391, -0.84816033,  0.49064271, -1.68194662, -0.31275983],
       [-0.595097  ,  0.31837169, -0.63979382, -0.03131222, -1.34731657],
       [-0.40319926, -0.71872087, -1.47265383,  1.34837704,  1.28556547],
       [-1.27718693, -1.01233964,  0.51947606,  1.21327388,  1.15139761],
       [-1.04535145,  0.38876984, -1.53958735, -0.94002732, -0.06677832],
       [-0.70880379,  1.55176845, -0.33058817,  0.29309254, -0.36725659]])

In [6]:
names == 'Islom' # bulieni == teng bulgan maulomotlarni chaqiradi

array([ True, False, False,  True, False, False, False])

In [7]:
# Boolien masking

data[names == "Islom"] # Islomga tegishli barcha qiymatlarni qaytaradi

array([[-0.91146962, -0.76622313,  1.6146796 ,  0.04663843, -0.09685263],
       [-0.40319926, -0.71872087, -1.47265383,  1.34837704,  1.28556547]])

In [8]:
data[names == "Siroj"]  # Sirojga tegishli barcha malumotlarni ajratib oladi

array([[-1.05639391, -0.84816033,  0.49064271, -1.68194662, -0.31275983]])

In [9]:
data[names == "Islom", 2:] # Islomga tegishli oldingi ikki ustundan keyingi malumotlarni ajratib olish

array([[ 1.6146796 ,  0.04663843, -0.09685263],
       [-1.47265383,  1.34837704,  1.28556547]])

In [10]:
data [names != 'Islom'] # != teng emas belgisi Islomga tegishli bulmagan barcha insonlarning malumotini ajratib olish

array([[-1.05639391, -0.84816033,  0.49064271, -1.68194662, -0.31275983],
       [-0.595097  ,  0.31837169, -0.63979382, -0.03131222, -1.34731657],
       [-1.27718693, -1.01233964,  0.51947606,  1.21327388,  1.15139761],
       [-1.04535145,  0.38876984, -1.53958735, -0.94002732, -0.06677832],
       [-0.70880379,  1.55176845, -0.33058817,  0.29309254, -0.36725659]])

In [11]:
data [~ (names == 'Islom')] # yuqoridagi ammal bilan birxil

array([[-1.05639391, -0.84816033,  0.49064271, -1.68194662, -0.31275983],
       [-0.595097  ,  0.31837169, -0.63979382, -0.03131222, -1.34731657],
       [-1.27718693, -1.01233964,  0.51947606,  1.21327388,  1.15139761],
       [-1.04535145,  0.38876984, -1.53958735, -0.94002732, -0.06677832],
       [-0.70880379,  1.55176845, -0.33058817,  0.29309254, -0.36725659]])

In [12]:
# Join condition
print(names)
print(data)

['Islom' 'Siroj' 'Shaxboz' 'Islom' 'Ozodbek' 'Suhrob' 'Dilshod']
[[-0.91146962 -0.76622313  1.6146796   0.04663843 -0.09685263]
 [-1.05639391 -0.84816033  0.49064271 -1.68194662 -0.31275983]
 [-0.595097    0.31837169 -0.63979382 -0.03131222 -1.34731657]
 [-0.40319926 -0.71872087 -1.47265383  1.34837704  1.28556547]
 [-1.27718693 -1.01233964  0.51947606  1.21327388  1.15139761]
 [-1.04535145  0.38876984 -1.53958735 -0.94002732 -0.06677832]
 [-0.70880379  1.55176845 -0.33058817  0.29309254 -0.36725659]]


In [15]:
mask = (names == 'Islom') | (names == 'Shaxboz') # "|" , or  (yoki) u yoki bu isimli insonga tegishli malumotlarni ajratadi
mask

array([ True, False,  True,  True, False, False, False])

In [16]:
data[mask, :2] # Islomga va Shaxbozga tegishli ma'lumotlani ajratib olish

array([[-0.91146962, -0.76622313],
       [-0.595097  ,  0.31837169],
       [-0.40319926, -0.71872087]])

In [17]:
data

array([[-0.91146962, -0.76622313,  1.6146796 ,  0.04663843, -0.09685263],
       [-1.05639391, -0.84816033,  0.49064271, -1.68194662, -0.31275983],
       [-0.595097  ,  0.31837169, -0.63979382, -0.03131222, -1.34731657],
       [-0.40319926, -0.71872087, -1.47265383,  1.34837704,  1.28556547],
       [-1.27718693, -1.01233964,  0.51947606,  1.21327388,  1.15139761],
       [-1.04535145,  0.38876984, -1.53958735, -0.94002732, -0.06677832],
       [-0.70880379,  1.55176845, -0.33058817,  0.29309254, -0.36725659]])

In [18]:
data[data<=0] = 0
data

array([[0.        , 0.        , 1.6146796 , 0.04663843, 0.        ],
       [0.        , 0.        , 0.49064271, 0.        , 0.        ],
       [0.        , 0.31837169, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.34837704, 1.28556547],
       [0.        , 0.        , 0.51947606, 1.21327388, 1.15139761],
       [0.        , 0.38876984, 0.        , 0.        , 0.        ],
       [0.        , 1.55176845, 0.        , 0.29309254, 0.        ]])