In [ ]:
import numpy as np

Indexing and Slicing

> Add blockquote



In [ ]:
arr = np.arange(10, 100, 10) # 10 to 90
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr1 = arr[3:5]

In [ ]:
arr1

array([40, 50])

In [ ]:
sliced_arr = arr[3:5]
sliced_arr[0]*2
sliced_arr

array([40, 50])

In [ ]:
sliced_arr[0] = sliced_arr[0]/2

In [ ]:
arr2 = np.arange(4)
arr2[2] = 5
arr2

array([0, 1, 5, 3])

In [ ]:
arr[4] = 3

In [ ]:
arr

array([10, 20, 30, 20,  3, 60, 70, 80, 90])

In [ ]:
 # copy() usuli haqida
 new_array = arr.copy()
 new_array[1] = 20
 new_array

array([10, 20, 30, 20,  3, 60, 70, 80, 90])

In [ ]:
# 2 o'lchamli (2d array) massivlardan indeks va kesib olish

arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2d[1, 2]

np.int64(5)

In [ ]:
arr2d[1, 1:]

array([4, 5])

In [ ]:
arr2d[1:,  1:]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2d[1:, ::2]

array([[3, 5],
       [6, 8]])

In [ ]:
np.random.seed(10)
arr3 = np.random.randn(9).reshape(3,3)
arr3

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143]])

In [ ]:
arr3[:2, 1:]

array([[ 0.71527897, -1.54540029],
       [ 0.62133597, -0.72008556]])

In [ ]:
arr3[:, :2]

array([[ 1.3315865 ,  0.71527897],
       [-0.00838385,  0.62133597],
       [ 0.26551159,  0.10854853]])

In [ ]:
arr3[1, :2]

array([-0.00838385,  0.62133597])

In [ ]:
# 3D array

arr3d = np.array([[[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]],

                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]],

                   [[19, 20, 21],
                   [22, 23, 24],
                   [25, 26, 27]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
arr3d [0, 2,2]

np.int64(8)

In [ ]:
arr3d[1][1:, 1:]

array([[14, 15],
       [17, 18]])

In [ ]:
arr3d[1:] [0:, :2, :2]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])