In [13]:
import numpy as np

In [18]:
# logical set
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) #yarr

In [19]:
# Shart
cond = np.array([True, False, True, True, False])

In [23]:
# where shart
results = np.where(cond, xarr, yarr) # cond ==True bulsa x arr oladi, cond == False bulsa yarr elementlardan oladi
results

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [22]:
arr = np.random.randn(6, 6) # (6 ga 6) taxminiy massiv
arr

array([[-0.2533072 ,  0.4802075 ,  0.21613153,  0.23554049, -1.09696669,
         0.3432656 ],
       [-0.16896046, -0.8455139 , -0.44416543, -0.96237538, -0.20075613,
         0.27150117],
       [ 0.27369624, -2.45841511, -0.46964997,  0.37993883,  0.03974829,
        -0.33191987],
       [ 0.50996101, -0.89914657, -0.06173669, -0.20122752, -0.0131778 ,
         0.57582599],
       [-0.53269301,  0.51966656, -0.42572031, -0.37212026,  1.00310959,
         0.32014138],
       [-0.73266662, -1.30368809,  0.19927892, -0.2375723 , -1.23909086,
        -0.88853542]])

In [24]:
# where
result = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarini esa 2 ga almashtirish
result

array([[-2,  2,  2,  2, -2,  2],
       [-2, -2, -2, -2, -2,  2],
       [ 2, -2, -2,  2,  2, -2],
       [ 2, -2, -2, -2, -2,  2],
       [-2,  2, -2, -2,  2,  2],
       [-2, -2,  2, -2, -2, -2]])