In [1]:
import numpy as np

In [4]:
arr = np.random.randn(5, 4) # (5, 4) o'lchov massiv (random)
arr

array([[-0.80222013, -1.29775835, -0.14128132, -1.09506977],
       [ 0.94285992, -0.77405414, -1.16937875, -1.34702939],
       [-1.30596744,  0.06763368,  2.69636867, -0.86597434],
       [-1.29079046,  1.18956501,  0.08481506, -0.16251903],
       [-0.75655239, -0.47444516, -1.89888962,  0.33649834]])

In [5]:
# sum metodi

In [6]:
arr.sum() # arr ning barcha elementlarini yigindisini hisoblab beradi

np.float64(-8.06418960736103)

In [7]:
arr.sum(axis=0) # ustun yig'indisi

array([-3.21267051, -1.28905897, -0.42836594, -3.13409419])

In [9]:
np.sum(arr) # arr ning barcha elementlarini yigindisini hisoblab beradi

np.float64(-8.06418960736103)

In [10]:
arr.sum(axis=1) # qator yi'g'indisi

array([-3.33632957, -2.34760236,  0.59206057, -0.17892942, -2.79338883])

In [11]:
# sodda malumotlar

data = np.arange(5)  # 0 ~ 5 gacha bo'lgan elementlardan tashkil topgan massiv
data

array([0, 1, 2, 3, 4])

In [12]:
mean = np.sum(data)/len(data)
mean

np.float64(2.0)

In [13]:
# numpy mean
np.mean(data)

np.float64(2.0)

In [14]:
arr

array([[-0.80222013, -1.29775835, -0.14128132, -1.09506977],
       [ 0.94285992, -0.77405414, -1.16937875, -1.34702939],
       [-1.30596744,  0.06763368,  2.69636867, -0.86597434],
       [-1.29079046,  1.18956501,  0.08481506, -0.16251903],
       [-0.75655239, -0.47444516, -1.89888962,  0.33649834]])

In [15]:
np.mean(arr) # arr ning o'rtacha qiymati

np.float64(-0.4032094803680515)

In [17]:
np.mean(arr, axis=1) # qator bo'yicha o'rtacha qiymarni qaytaradi

array([-0.83408239, -0.58690059,  0.14801514, -0.04473236, -0.69834721])

In [19]:
arr.mean(axis=0) # ustunlar bo'yicha o'rtacha qiymati qaytaradi

array([-0.6425341 , -0.25781179, -0.08567319, -0.62681884])

In [20]:
# cunsum metodi

In [21]:
data

array([0, 1, 2, 3, 4])

In [24]:
data.cumsum() # cumilative sum - 0, 0+1, 1+2, 1+2+3, 1+2+3+4

array([ 0,  1,  3,  6, 10])

In [26]:
data = np.array([1,2,3,4]) # cumilative product means 1, 1x2, 1x2x3, 1x2x3x4
data.cumprod()

array([ 1,  2,  6, 24])