In [ ]:
import numpy as np

In [ ]:
# tezlika farq

my_list = list(range(20000)) #0, 20000 (list)
my_array = np.arange(2000) # 0, 2000 (array)

my_array


array([   0,    1,    2, ..., 1997, 1998, 1999])

In [ ]:
%%time
for _ in range(2000): [x*2 for x in my_list] #Normal

CPU times: user 1.38 s, sys: 0 ns, total: 1.38 s
Wall time: 1.39 s


In [ ]:
%%time
for _ in range(2000): my_array*2

CPU times: user 5.67 ms, sys: 0 ns, total: 5.67 ms
Wall time: 5.67 ms


In [ ]:
l1 = [1, 2, 3]
l1*2

[1, 2, 3, 1, 2, 3]

In [ ]:
arr1 = np.array([1, 2, 3])
arr1*2

array([2, 4, 6])

In [ ]:
# Array yaratish
data = [2.5, 4, 5, 6]
arr1 = np.array(data)
arr1

array([2.5, 4. , 5. , 6. ])

In [ ]:
data

[2.5, 4, 5, 6]

In [ ]:
arr1

array([2.5, 4. , 5. , 6. ])

In [ ]:
data2 =(4, 9, 2.1, 1) #tuple
arr2 = np.array(data2)

In [ ]:
arr2

array([4. , 9. , 2.1, 1. ])

In [ ]:
# Massiv o'lchamli (ndim)

arr2.ndim

1

In [ ]:
# Ikki va undan katta o'lchamli massivlar

data3 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr3 = np.array(data3)

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.ndim

2

In [ ]:
# shape, size attributlar

In [ ]:
arr2

array([4. , 9. , 2.1, 1. ])

In [ ]:
arr2.shape

(4,)

In [ ]:
 arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.shape

(2, 4)

In [ ]:
# size
arr2.size

4

In [ ]:
arr3.size

8

In [ ]:
 # N-o'lchamli massivlar yaratishning boshqa usullari

# zeros va ones funksiyalari yotdamida massivlar yaratish

In [ ]:
arr4 = np.zeros((2, 4)) # 2x4 o'lchamli barcha elementlari 0 dan iborat array

In [ ]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((2, 4)) # 2x4 o'lchamli barcha elementlari 1 dan iborat array

In [ ]:
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# arange
arr6 = np.arange(5, 30, 4)

In [ ]:
arr6

array([ 5,  9, 13, 17, 21, 25, 29])

In [ ]:
# random
np.random.seed(4)
arr7 = np.random.rand(2, 4)
arr7

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026]])

In [ ]:
# Normal distribution sampling
np.random.seed(4)
arr8 = np.random.randn(4, 8)

In [ ]:
arr8

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152,
        -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693,  0.4250724 ,
         0.33225315, -1.15681626,  0.35099715],
       [-0.60688728,  1.54697933,  0.72334161,  0.04613557, -0.98299165,
         0.05443274,  0.15989294, -1.20894816],
       [ 2.22336022,  0.39429521,  1.69235772, -1.11281215,  1.63574754,
        -1.36096559, -0.65122583,  0.54245131]])

In [ ]:
arr9 = np.random.randint(2, 5 , size = (2,4))

In [ ]:
arr9

array([[3, 3, 3, 2],
       [4, 4, 2, 4]])

In [ ]:
eye = np.eye(4)

In [ ]:
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Massivlar yaratish

arr10 = np.array([1, 2, 3], dtype = np.int32)

In [ ]:
arr10

array([1, 2, 3], dtype=int32)

In [ ]:
arr10.itemsize

4

In [ ]:
arr10.nbytes

12

In [ ]:
arr9

array([[3, 3, 3, 2],
       [4, 4, 2, 4]])

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
arr8[0, 1] = 2

In [ ]:
arr8

array([[ 0.05056171,  2.        , -0.99590893,  0.69359851, -0.41830152,
        -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693,  0.4250724 ,
         0.33225315, -1.15681626,  0.35099715],
       [-0.60688728,  1.54697933,  0.72334161,  0.04613557, -0.98299165,
         0.05443274,  0.15989294, -1.20894816],
       [ 2.22336022,  0.39429521,  1.69235772, -1.11281215,  1.63574754,
        -1.36096559, -0.65122583,  0.54245131]])

In [ ]:
arr9[0, 2] = 1.9
arr9

array([[3, 3, 1, 2],
       [4, 4, 2, 4]])

In [ ]:
# bir turdagi ma'lumotlarni boshqa turga ogirish

arr11 = np.random.randn(2, 5) #2x5 normal dist.dan sampling
arr11

array([[ 0.09739415, -0.10913821,  0.6752176 ,  1.02096908,  0.52845098],
       [ 0.18180266, -0.11186876, -1.59203303,  0.72865586, -0.33880365]])

In [ ]:
arr11.astype(np.int64) # int64 dtypega o'girish

array([[ 0,  0,  0,  1,  0],
       [ 0,  0, -1,  0,  0]])