In [12]:
#california fataset bilan bivariate analysis otkazish
#vazifa test, covariance correlation bivariate hisoblash
#keyingi darsdan keyin koproq practal boladi shunga numpy pandas practice qilish kerak self-study
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [13]:
#median_income median_house_value shu 2ta feature ni oldim
data1 = df['median_income']
data2 = df['median_house_value']

data1_list = df['median_income'].values.tolist()
data2_list = df['median_house_value'].values.tolist()


In [14]:
#covariance
def cal_covariance(data1, data2):
    if len(data1) != len(data2):
        raise ValueError("ikta list teng emas")

    n = len(data1)
    mean_data1 = sum(data1)/n
    mean_data2 = sum(data2)/n

    cov = sum((data1[i]-mean_data1)*(data2[i] - mean_data2) for i in range(n)) / n

    return cov

cal_covariance(data1, data2)

np.float64(150840.17429058775)

In [15]:
df[['median_income', 'median_house_value']].cov()

median_income  median_house_value
median_income            3.609323        1.508475e+05
median_house_value  150847.482793        1.331615e+10

In [17]:
#correlation
def cal_correlation(x1, x2):
    if len(x1) != len(x2):
        raise ValueError('ikta list teng emas')
    
    n = len(x1)
    mean_x1 = sum(x1)/n
    mean_x2 = sum(x2)/n

    cov = sum((x1[i]-mean_x1)*(x2[i]-mean_x2) for i in range(n))/n
    std_x1 = (sum((i-mean_x1)**2 for i in x1)/n) ** 0.5
    std_x2 = (sum((i-mean_x2)**2 for i in x2)/n) ** 0.5

    corr = cov/(std_x1*std_x2)

    return corr

cal_correlation(data1_list, data2_list)



0.6880752079585478

In [16]:
df[['median_income', 'median_house_value']].corr()


median_income  median_house_value
median_income            1.000000            0.688075
median_house_value       0.688075            1.000000

In [18]:
def calculate_pdf_vectorized(data):
    mu = np.mean(data)  # Calculate the mean of the dataset
    sigma = np.std(data, ddof=1)  # Calculate the standard deviation of the dataset
    coeff = 1 / (sigma * np.sqrt(2 * np.pi))  # Precompute the coefficient
    
    # Compute the exponent part for all data points in one go
    exponent = np.exp(-((data - mu) ** 2) / (2 * sigma ** 2))
    
    # Return the array of computed PDF values
    return coeff * exponent
pdf_value = calculate_pdf_vectorized(data1_list)
pdf_value

array([0.01343988, 0.01383943, 0.04286798, ..., 0.10932538, 0.12042306,
       0.15489856], shape=(20640,))

In [19]:
pdf_value2 = calculate_pdf_vectorized(data2_list)
pdf_value2

array([3.58042039e-07, 1.45788834e-06, 1.56570188e-06, ...,
       2.11213961e-06, 1.97417697e-06, 2.05944728e-06], shape=(20640,))

In [20]:
def min_max(data):
    min_val = np.min(data)
    max_val = np.max(data)
    return (data-min_val)/(max_val-min_val)
data = df['median_income'].values
min_max(data)

array([0.53966842, 0.53802706, 0.46602805, ..., 0.08276438, 0.09429525,
       0.13025338], shape=(20640,))