#tezlikdagi farq

In [3]:
import numpy as np

In [4]:
my_list=list(range(10000))
my_array=np.arange(10000)

In [8]:
%%time
for _ in range(100): [x*2 for x in my_list]

CPU times: user 35.3 ms, sys: 3.81 ms, total: 39.1 ms
Wall time: 39 ms


In [7]:
%%time
for _ in range(100): my_array*2

CPU times: user 2.46 ms, sys: 0 ns, total: 2.46 ms
Wall time: 2.37 ms


In [10]:
l1=[1,2,3]
l1*2

[1, 2, 3, 1, 2, 3]

In [12]:
arr1=np.array([1,2,3])
arr1*2

array([2, 4, 6])

**Array yaratish**

In [13]:
data=[3.5, 5,6,2] #list

In [16]:
arr2=np.array(data)
arr2

array([3.5, 5. , 6. , 2. ])

In [17]:
data

[3.5, 5, 6, 2]

In [20]:
data2=(4,5,3.2,7) # tuple
arr3=np.array(data2)
arr3

array([4. , 5. , 3.2, 7. ])

#Massiv o‘lchami (ndim)

In [22]:
arr2.ndim

1

In [25]:
data3=[[1,2,3,4],[5,6,7,8]]
arr4=np.array(data3)
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr4.ndim

2

shape, size

In [27]:
arr3

array([4. , 5. , 3.2, 7. ])

In [28]:
arr3.shape

(4,)

In [29]:
arr4.shape

(2, 4)

N-o‘lchamli massivlar yaratishning boshqa usullari

zeros va ones funksiyalari yordamida massiv yaratish

In [31]:
arr5=np.zeros((2,4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr6=np.ones((2,4))
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
#arange yordamida
arr7=np.arange(4, 20, 2)
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
#random
np.random.seed(42) # fixid qilish
arr8=np.random.rand(2,4)
arr8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [41]:
# Normal distribution
arr8=np.random.randn(2,4)
arr8

array([[-1.72491783, -0.56228753, -1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ]])

In [43]:
arr9=np.random.randint(10, size=(2,4))
arr9

array([[4, 8, 6, 1],
       [3, 8, 1, 9]])

ones_like, zeros_like

In [44]:
eye=np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Numpy kutubxonasi ma'lumot turlari

In [49]:
arr10=np.array([1,2,3], dtype=np.int16)
arr10

array([1, 2, 3], dtype=int16)

In [53]:
arr10.itemsize #testga

2

In [51]:
arr10.nbytes

6

In [58]:
arr8.dtype

dtype('float64')

In [60]:
arr8[0,1]=4
arr8.dtype

dtype('float64')

In [61]:
arr9

array([[4, 8, 6, 1],
       [3, 8, 1, 9]])

In [63]:
arr9[0,2]=0.1  # ma'lumot yo'qoladi
arr9

array([[4, 8, 0, 1],
       [3, 8, 1, 9]])

In [66]:
arr11=np.random.randn(2,5)
arr11

array([[-0.60063869, -0.29169375, -0.60170661,  1.85227818, -0.01349722],
       [-1.05771093,  0.82254491, -1.22084365,  0.2088636 , -1.95967012]])

In [68]:
arr11.astype(np.int64) # convertasiya, testga

array([[ 0,  0,  0,  1,  0],
       [-1,  0, -1,  0, -1]])

#Indexing

In [70]:
arr=np.arange(10, 100, 10) #10 dan 90 gacha
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Slicing

In [72]:
arr[3:5]

array([40, 50])

In [76]:
sliced_arr=arr[3:5]
sliced_arr[0]*2

np.int64(80)

In [77]:
sliced_arr[0]/2
sliced_arr

array([40, 50])

In [78]:
arr1=np.arange(4)
arr1

array([0, 1, 2, 3])

In [79]:
arr1[2]=5
arr1

array([0, 1, 5, 3])

In [80]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#Copy usuli

In [81]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
new_array=arr.copy()
new_array[1]=25

In [86]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
new_array

array([10, 25, 30, 40, 50, 60, 70, 80, 90])

# 2D array

In [90]:
arr2d=np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr2d[1, 2]

np.int64(5)

In [94]:
arr2d[1, 1:]

array([4, 5])

In [96]:
arr2d[1:, 1:]

array([[4, 5],
       [7, 8]])

In [97]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
arr2d[1:, ::2]  ##:: qadam (step) berish

array([[3, 5],
       [6, 8]])

In [101]:
arr2d[-2:, -3::2]

array([[3, 5],
       [6, 8]])

#3D array

In [102]:
arr3d=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                  [16,17,18]],
                [[19,20,21],
                 [22,23,24],
                  [25,26,27]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [103]:
arr3d[0][2,2]

np.int64(9)

In [104]:
arr3d[0,2,2]

np.int64(9)

In [105]:
arr3d[1,1:, 1:]

array([[14, 15],
       [17, 18]])

In [109]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [113]:
arr3d[1:, 1:, :2]

array([[[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]]])

#Math statistic

In [115]:
arr=np.random.randn(5,4)
arr

array([[ 0.33126343,  0.97554513, -0.47917424, -0.18565898],
       [-1.10633497, -1.19620662,  0.81252582,  1.35624003],
       [-0.07201012,  1.0035329 ,  0.36163603, -0.64511975],
       [ 0.36139561,  1.53803657, -0.03582604,  1.56464366],
       [-2.6197451 ,  0.8219025 ,  0.08704707, -0.29900735]])

#SUM

In [116]:
arr.sum()

np.float64(2.574685550385559)

In [120]:
arr.sum(axis=0)  #satr yig'indi testga

array([-3.10543116,  3.14281047,  0.74620864,  1.7910976 ])

In [121]:
arr.sum(axis=1) #qator yig'indi testga

array([ 0.64197534, -0.13377575,  0.64803905,  3.42824979, -2.00980288])

MEAN

In [123]:
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [124]:
np.mean(data)

np.float64(2.0)

In [125]:
arr

array([[ 0.33126343,  0.97554513, -0.47917424, -0.18565898],
       [-1.10633497, -1.19620662,  0.81252582,  1.35624003],
       [-0.07201012,  1.0035329 ,  0.36163603, -0.64511975],
       [ 0.36139561,  1.53803657, -0.03582604,  1.56464366],
       [-2.6197451 ,  0.8219025 ,  0.08704707, -0.29900735]])

In [127]:
np.mean(arr, axis=1) # ustun bo'yicha

array([ 0.16049384, -0.03344394,  0.16200976,  0.85706245, -0.50245072])

In [128]:
np.mean(arr, axis=0) # satr bo'yicha

array([-0.62108623,  0.62856209,  0.14924173,  0.35821952])

#cumsum metodi

In [133]:
data.cumsum() #testga

array([ 1,  3,  6, 10])

In [132]:
data=np.array([1,2,3,4])
data.cumprod() # testga

array([ 1,  2,  6, 24])

#Boolean indexing

In [136]:
names=np.array(["Hasan", "Husan", 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])

In [137]:
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [138]:
data=np.random.randn(7,4)
data

array([[ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743],
       [ 0.09707755,  0.96864499, -0.70205309, -0.32766215],
       [-0.39210815, -1.46351495,  0.29612028,  0.26105527],
       [ 0.00511346, -0.23458713, -1.41537074, -0.42064532],
       [-0.34271452, -0.80227727, -0.16128571,  0.40405086]])

In [139]:
names=='Hasan'

array([ True, False, False, False,  True, False, False])

In [140]:
data[names=='Hasan']

array([[ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [-0.39210815, -1.46351495,  0.29612028,  0.26105527]])

In [141]:
data[names=='Elyor']

array([[ 0.09707755,  0.96864499, -0.70205309, -0.32766215],
       [-0.34271452, -0.80227727, -0.16128571,  0.40405086]])

In [142]:
data[names=='Hasan', 2:]

array([[-0.21967189,  0.35711257],
       [ 0.29612028,  0.26105527]])

In [143]:
data[names!='Hasan', 2:]

array([[-0.8084936 , -0.50175704],
       [-0.5297602 ,  0.51326743],
       [-0.70205309, -0.32766215],
       [-1.41537074, -0.42064532],
       [-0.16128571,  0.40405086]])

In [146]:
data[~(names=='Hasan'), 2:]

array([[-0.8084936 , -0.50175704],
       [-0.5297602 ,  0.51326743],
       [-0.70205309, -0.32766215],
       [-1.41537074, -0.42064532],
       [-0.16128571,  0.40405086]])

In [147]:
mask=(names=='Hasan')|(names=='Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [148]:
data[mask]

array([[ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [-0.39210815, -1.46351495,  0.29612028,  0.26105527]])

In [151]:
data[mask, :2]

array([[ 0.09176078, -1.98756891],
       [ 1.47789404, -0.51827022],
       [-0.39210815, -1.46351495]])

In [150]:
data

array([[ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743],
       [ 0.09707755,  0.96864499, -0.70205309, -0.32766215],
       [-0.39210815, -1.46351495,  0.29612028,  0.26105527],
       [ 0.00511346, -0.23458713, -1.41537074, -0.42064532],
       [-0.34271452, -0.80227727, -0.16128571,  0.40405086]])

In [152]:
data[data<0]=0
data

array([[0.09176078, 0.        , 0.        , 0.35711257],
       [1.47789404, 0.        , 0.        , 0.        ],
       [0.91540212, 0.32875111, 0.        , 0.51326743],
       [0.09707755, 0.96864499, 0.        , 0.        ],
       [0.        , 0.        , 0.29612028, 0.26105527],
       [0.00511346, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.40405086]])

#Logical_set

In [156]:
#massivlar
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])


In [157]:
#shart
cond=np.array([True, False, True, True, False])

In [158]:
#where
result=np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [161]:
arr=np.random.randn(4,4)
arr

array([[ 1.8861859 ,  0.17457781,  0.25755039, -0.07444592],
       [-1.91877122, -0.02651388,  0.06023021,  2.46324211],
       [-0.19236096,  0.30154734, -0.03471177, -1.16867804],
       [ 1.14282281,  0.75193303,  0.79103195, -0.90938745]])

In [162]:
#where
results=np.where(arr<0, -2,2) # arr ning manfiy elementlarini -2 ga, musbat elementlarin ese 2 ga almashtiradi
results

array([[ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [-2,  2, -2, -2],
       [ 2,  2,  2, -2]])