In [2]:
import torch

if torch.cuda.is_available():
    gpu = torch.cuda.get_device_properties(0)
    print(f"Name: {gpu.name}")
    print(f"Total Memory: {gpu.total_memory / 1024**2:.0f} MB (Dedicated VRAM)")
    print(f"Shared Memory not directly reported here (system RAM).")
else:
    print("No GPU available.")

No GPU available.


#1. Array yasash
N-o'lchamli massiv (array)larga ishlov berish

In [3]:
import numpy as np

In [4]:
# from list 
my_list = list(range(100))
arr = np.array(my_list)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
# from  tuple
my_tuple = tuple(range(100))
arr1 = np.array(my_tuple)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
# with np.arange() function
arr2 = np.arange(100)
arr2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
# np.arange() function with step 5
arr3 = np.arange(0,100,5)
arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

#2. Massiv o'lchami (`ndim`)

In [8]:
arr2.ndim      # find dimension of arr2

1

#3. Ikki va undan katta o'lchamli massivlar

In [9]:
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])   # make 2D array
arr3.ndim

2

In [10]:
arr4 = np.array([[[1,2,3],[4,5,6]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]]])

In [11]:
arr4.ndim

3

In [12]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])   # make 3D array
arr5

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [13]:
arr5.ndim

3

In [14]:
arr6 = np.array([1,2,3,4,5], ndmin = 3)     # give dimension with 'ndmin' attribute
arr6.ndim

3

#4. `shape` , `size` atributlari
`shape` atributi massivning qator va ustunlar sonini ko'rsatsa, `size` esa massivlardagi elementlar sonini nomoyon etadi

In [15]:
arr6.shape    # xar bir dimension dagi elementlar soni

(1, 1, 5)

In [16]:
arr7  = np.arange(1,25,2)
arr7.shape = (4,3)             # set shape of array
arr7

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [17]:
arr6.size # umumiy elementlar soni

5

#5. N-o'lchamli massivlar yaratishning boshqa usullari
`zeros` va `ones` funksiyalari yordamida massivlar yaratish  `random` `normal distribution`

In [18]:
arr_zeros = np.zeros(shape=(2,3))    # faqat nol li array
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr_ones = np.ones(shape=(3,2))      # faqat 1 lik array
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
arr_eyes = np.eye(3)     # 3x3 diagonal birlik array
arr_eyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr_full = np.full((2,3), 5)  # 2x3  '5' lik array
arr_full

array([[5, 5, 5],
       [5, 5, 5]])

In [22]:
arr_random = np.random.rand(2,3)  # 0 ~ 1 gacha range da 2x3 array 
arr_random

array([[0.32733816, 0.10517561, 0.84229651],
       [0.82897194, 0.95778525, 0.67652699]])

In [23]:
arr_rand_integer = np.random.randint(1,10, size=(3,3))   # 1 ~ 10 gacha rangeda integer   li 3x3 shape array. 'size' bu yerda 'shape' 
arr_rand_integer

array([[8, 3, 4],
       [3, 8, 3],
       [8, 5, 4]])

In [24]:
arr_rand_integer.shape

(3, 3)

In [25]:
arr_rand_normal = np.random.randn(2,3) # normal distribution li 2x3 array    
arr_rand_normal

array([[-0.13034621, -0.65369066,  1.53009263],
       [-1.3631815 , -0.99355364, -1.1327487 ]])

In [26]:
arr7 = np.linspace(0,10, 3)    # (0,10) range da teng oraliqdagi 3 ta raqam (float)
arr7

array([ 0.,  5., 10.])

#6. Massivlar yaratishda ma'lumot turlarini aniq kiritish, ma'lumot turlarini aniqlash, bir turdagi ma'lumot turidan ikkinchi turdagi ma'lumot turiga o'girish


    i - integer                                        int8, int16, int32, int64
    b - boolean                                        true/flase   bool_
    u - unsigned integer                               uint8, uint16, uint32, uint64
    f - float                                          float16, float32, float64, float128
    c - complex float                                  complex64, complex128, complex256
    m - timedelta                                      timedelta64
    M - datetime                                       datetime64
    O - object                                         object_
    S - string                                         S10 = string of max length 10 bytes
    U - unicode string                                 U10 = string of max length 10 chars
    V - fixed chunk of memory for other type (void)  V8 = 8-byte record


In [27]:
arr8 = np.array(['olma', 'behi', 'anor'])
arr8                                         # maximum 4ta belgili unicode string dtype 

array(['olma', 'behi', 'anor'], dtype='<U4')

In [28]:
arr9 = np.array(my_list, dtype='float16')    # array dtype ni belgilab ketish
arr9

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.], dtype=float16)

#7.Bir turdagi ma'lumot turidan boshqasiga o'girish

In [29]:
arr9.dtype

dtype('float16')

In [30]:
arr10 = arr9.astype('int16')    # change arr10 dtype from float16 to int16
arr10.dtype

dtype('int16')

In [31]:
arr11 = np.array([1,2,3], dtype='float16')
arr11.itemsize    # array 1ta elementini byte dagi o'lchovi. dtype ga bogliq uzgaradi

2

In [32]:
arr11.nbytes  # array ni memory dagi joy olishi.    nybytes  = itemsize*shape

6

#8. N-o'lchamli massiv (array)larga ishlov berish

 Indeks va kesib olish asoslari

In [33]:
arr12 = np.arange(0,100,5)
arr12

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [34]:
arr12.size

20

In [35]:
arr12[5:15]             # array slice [5:15]

array([25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

#9. `copy` usuli haqida

In [36]:
arr13 = arr12.copy()   # arraydan copy olish
arr13

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

#10. 2 o'lchamli (2d array) massivlarda indeks va kesib olish

In [37]:
arr14 = np.arange(0,100,5)
arr14_2d = arr14.reshape(4,5)    # check array size. size must be equal to col*row
arr14_2d

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [ ]:
arr14_2d[-1,-1]    # oxirgi row dagi oxirgi element

95

#11. 2-o'lchamli massivlarning bir nechta elementlarini kesib olish

In [ ]:
arr14_2d[1, :]     # 2 qator hammasi

array([25, 30, 35, 40, 45])

In [ ]:
arr14_2d[1:, 3:]   # 2-qatordan oxirigacha 4-ustundan oxirigacha joylashgan elementlar

array([[40, 45],
       [65, 70],
       [90, 95]])

In [ ]:
arr14_2d[0::2,0::2]  # 0 qatordan oxirgacha 2step bn 0 ustundan oxirgacha 2step bn joylashgan elementlar

array([[ 0, 10, 20],
       [50, 60, 70]])

#12. 3-o'lchamli massivlarda indeks va kesib olish asoslari

In [ ]:
arr15 = np.arange(27)  
arr15_3d = arr15.reshape(3,3,3)  # reshape 1D to 3D . array size (27) = block*row*col (3x3x3)
arr15_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr15_3d[1,1,1]   # = arr15_3d[1][1,1]  2-blok 2-qator 2 -ustundagi element 

13

In [78]:
arr15_3d[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr15_3d[::2][:,::2] # [::2] hamma blokdan 2step bn blok oladi [:,::2] qolgan blok dan 2step bn row larni oladi 

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [24, 25, 26]]])

In [80]:
arr15_3d[:, 1:, 1: ]

array([[[ 4,  5],
        [ 7,  8]],

       [[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]]])

In [81]:
arr15_3d[1:3, 1:3, :2]

array([[[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

#13. Matematik va Statistik usullarni qo'llash
 `sum` metodi

In [ ]:
arr15_3d.sum()  # arr ning barcha elementlarni yig'indisini hisoblab beradi


351

In [ ]:
arr15_3d.sum(axis=(0,2)) # row sums across whole 3D array

array([ 90, 117, 144])

In [88]:
arr15_3d.sum(axis=2) # xar bitta row ning yigindisi

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

In [89]:
arr15_3d.sum(axis=(0,1)) #  column sums across the whole 3D array

array([108, 117, 126])

In [ ]:
arr15_3d.sum(axis=1) # xar bitta col  ning yigindisi

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

#14. `mean` metodi

In [96]:
# sodda ma'lumot
# code # 0 ~ 5 gacha bo'lgan elementlarda tashkil topgan massiv

arr16 = np.arange(5)
arr16

array([0, 1, 2, 3, 4])

In [97]:
arr16.mean() # numpy mean

2.0

In [99]:
arr15_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
arr15_3d.mean() # arr ning o'rtacha qiymati

13.0

In [ ]:
arr15_3d.mean(axis=2)  # xar bir row uchun mean 

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

In [ ]:
arr15_3d.mean(axis=(0,2)) # jami qatorlar bo'yich o'rtach qiymat

array([10., 13., 16.])

In [102]:
arr15_3d.mean(axis=1)  # xar bir ustun bo'yicha o'rtacha qiymat

array([[ 3.,  4.,  5.],
       [12., 13., 14.],
       [21., 22., 23.]])

In [103]:
arr15_3d.mean(axis=(0,1)) # jami ustunlar bo'yich o'rtach qiymat

array([12., 13., 14.])

#15. `cumsum` metodi

In [ ]:
 #cumilative sum
arr15_3d.cumsum()


array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351])

In [ ]:
 #calculate the covariance                  3d Shape = (3, 3, 3) → (depth, rows, cols).
cov_arr = np.arange(10).reshape(2,5)       
cov = np.cov(cov_arr)
cov

array([[2.5, 2.5],
       [2.5, 2.5]])

### N-o'lchamli massiv (array)larga ishlov berish

#16. Bolean Indekslash

In [110]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])

###   Massivga yo'naltirilgan dasturlash. Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

#17. Shart operatori sifatida `where` dan foydalanish

In [ ]:
a = np.where(names == 'Hasan')    
a

(array([0, 4], dtype=int64),)

###. Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [114]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [115]:
# Shart
cond = np.array([True, False, True, True, False])

In [116]:
# where
new_arr = np.where(cond,xarr,yarr)
new_arr

array([1.1, 2.2, 1.3, 1.4, 2.5])

###  N-o'lchamli massiv (array)larga ishlov berish. Massivlar pozitsiyasini ko'chirish `Transpose` va o'qlar o'rnini almashtirish `Swapping axes`

#18.`reshape` metodi

In [ ]:
arr18 = np.arange(20)

arr18_2d = arr18.reshape(4,5)         # 1d to 2d      size = row x col
arr18_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#19. `Transpose`

In [ ]:
arr18_2d.T     # transpose 

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

#20. `swaping axes`

In [129]:
swap_arr = np.swapaxes(arr18_2d, 0 , 1)     # transpose ga uxshash
swap_arr

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

#21. `Tranpose`ning ishlatilinishiga bir misol $A A^T$

In [130]:
np.dot(arr18_2d, arr18_2d.T) # AA^T hosil bo'lgan massiv

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

In [138]:

s = np.ndarray(list(range(0,10,2)))
s

array([], shape=(0, 2, 4, 6, 8), dtype=float64)

In [ ]:
b = np.arange(0:10,2)
b

array([0, 2, 4, 6, 8])