In [ ]:
# Chiziqli algebra asoslari va uni numpyda qullanilishi
# 5-dars
# Numpy

In [1]:
import numpy as np

In [ ]:
# tezlikdagi farqi
my_list = list(range(10000)) #0, 10000 list
#my_list
my_array = np.arange(10000) #0, 10000 array
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
%%time
for _ in range(100): [x*2 for x in my_list] # Normal

CPU times: user 33.4 ms, sys: 0 ns, total: 33.4 ms
Wall time: 33.4 ms


In [ ]:
%%time
for _ in range(100): my_array * 2 # with Numpy

CPU times: user 1.88 ms, sys: 6 µs, total: 1.88 ms
Wall time: 1.64 ms


In [ ]:
l1 = [1,2,3]
l1 * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
ar1 = np.array([1,2,3])
ar1 * 2

array([2, 4, 6])

In [ ]:
# 1 Array yaratish
#data yaratish

data = [3.5,5,6,2]
arr2 = np.array(data)
arr2
print(type(arr2))
print(type(data))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
data2 = (4,5,3.2,7)
arr3 = np.array(data2)
arr3

array([4. , 5. , 3.2, 7. ])

In [ ]:
# Massiv o'lchami (ndim)

arr2.ndim

1

In [ ]:
# Ikki va undan katta o'lchamli massivlar

data3 = [[1,2,3,4],[5,6,7,8]]
arr4 = np.array(data3)
print(arr4)
print(arr4.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
# Shape and Size
# shape atributi massivning qatori va ustunlar sonini ko'rsatsa, size massivdagi elementlar sonini ko'rsatadi
print(arr4)
print(arr4.shape)   #(x,y) -- x- (yoki axis0 )bu qator soni, y- (yoki axis1 )bu ustun soni hisoblanadi,

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
# Size
print(arr4)
print(arr4.size)  # size bu nechta element borligini soni

[[1 2 3 4]
 [5 6 7 8]]
8


In [ ]:
# N-o'lchovli massivlarni yaratishning boshqa usullari
# zeros va ones funksiyalari yordamida array yaratish

arr5 = np.zeros((2,5))
arr5


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((2,4))   # np.ones((x,y)) x- qator soni, y-ustun soni
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# arange
arr7 = np.arange(4,20,3)    # np.arange(x,y,z) holatda, x-boshlanishi, y-tugashi (lekin o'zi kirmaydi), z-nechta qadam sakrash
arr7

array([ 4,  7, 10, 13, 16, 19])

In [ ]:
# random
arr8 = np.random.rand(3,4)
arr8

array([[0.1576262 , 0.91305319, 0.69152405, 0.58196117],
       [0.86068938, 0.59023578, 0.06483709, 0.35113358],
       [0.01492652, 0.16096805, 0.16007683, 0.27126073]])

In [ ]:
# random
np.random.seed(42)   # np.random.seed(42) -- bu random tanlaydi lekin keyingi safar kodni qayta ishga tushirsa o'zgarmaydi
arr81 = np.random.rand(2,3)
arr81

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [ ]:
print(arr8.ndim)

2


In [ ]:
# Normal distribution sampling

arr82 = np.random.randn(2,4)
arr82

array([[-0.60170661,  1.85227818, -0.01349722, -1.05771093],
       [ 0.82254491, -1.22084365,  0.2088636 , -1.95967012]])

In [ ]:
# Integer sonlardan random tanlash
arr9 = np.random.randint(7, size=(3,5))  # np.random.randint(x, size(a,b)), bu yerda x - maximum integer qiymat, a va b row and colm
arr9

array([[0, 1, 1, 3, 5],
       [6, 4, 0, 0, 2],
       [5, 1, 4, 3, 1]])

In [ ]:
#### Numpy funksiyalarini o'rganish

In [ ]:
np.zeros_like(arr9)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones_like(arr8)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
eye = np.eye(4) # diaganalini 1 ga qolgan qiymatlarini 0 ga teng bo'ladi
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Data typelar
arr10 = np.array([1,2,3], dtype = np.int16)

In [ ]:
arr10.itemsize     # bu dataning nechi size ekanligini ko'rsatadi

2

In [ ]:
arr10.nbytes      # bu ma'lumot necha baytdan iborat ekanligini ko'rsatadi

6

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
arr8

array([[0.1576262 , 1.        , 0.69152405, 0.58196117],
       [0.86068938, 0.59023578, 0.06483709, 0.35113358],
       [0.01492652, 0.16096805, 0.16007683, 0.27126073]])

In [ ]:
arr8[0,1] = 1
arr8

array([[0.1576262 , 1.        , 0.69152405, 0.58196117],
       [0.86068938, 0.59023578, 0.06483709, 0.35113358],
       [0.01492652, 0.16096805, 0.16007683, 0.27126073]])

In [ ]:
arr9

array([[0, 1, 1, 3, 5],
       [6, 4, 0, 0, 2],
       [5, 1, 4, 3, 1]])

In [ ]:
arr9[1,1] = 0.1
arr9

array([[0, 1, 1, 3, 5],
       [6, 0, 0, 0, 2],
       [5, 1, 4, 3, 1]])

In [ ]:
arr11 = np.random.randn(2,5) # 2x5 normal distribution sampling random
arr11

array([[-0.84679372, -1.51484722, -0.44651495,  0.85639879,  0.21409374],
       [-1.24573878,  0.17318093,  0.38531738, -0.88385744,  0.15372511]])

In [ ]:
print(arr11.dtype)

float64


In [ ]:
arr11.astype(np.int64)

array([[ 0, -1,  0,  0,  0],
       [-1,  0,  0,  0,  0]])

In [ ]:
# Indeks va kesib olish
arr12 = np.arange(10,100,10) # 10dan 100 gacha
arr12

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr12[3:5]

array([40, 50])

In [ ]:
sliced_arr12 = arr12[3:5]
print(sliced_arr12)

[40 50]


In [ ]:
print(sliced_arr12[0]*2)
print(sliced_arr12[1]*3)

80
150


In [ ]:
sliced_arr12[0]/2

np.float64(20.0)

In [ ]:
arrr1 = np.arange(4)
arrr1

array([0, 1, 2, 3])

In [ ]:
new_arrr1 = np.copy(arrr1)  # nusxa ovoladi
new_arrr1

array([0, 1, 2, 3])

In [ ]:
######################### 2D array#####################################

In [ ]:
from re import A
arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print(arr2d[1,2])  # yuqoridagi arr2d dan besh (5) ni ajratib olish

5


In [ ]:
arr2d[1,1:] # # yuqoridagi arr2d dan besh (5) va 4 ni ajratib olish

array([4, 5])

In [ ]:
arr2d[0:2,0:2]   # yuqoridagi arr2d dan [0,1], [3,4] ni ajratib olish

array([[0, 1],
       [3, 4]])

In [ ]:
arr2d[1:,0::2]  ## :: qadam tashlash uchun ishlatiladi

array([[3, 5],
       [6, 8]])

In [ ]:
## 3D array

arr3d = np.array([[[0,1,2],
                   [3,4,5],
                   [6,7,8]],
                  [[9,10,11],
                   [12,13,14],
                   [15,16,17]],
                  [[18,19,20],
                   [21,22,23],
                   [24,25,26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d_8 = arr3d[0][2,2]  ## yuqoridan 8 ni ajratib olish
print(arr3d_8)

8


In [ ]:
sliced_arr3d = arr3d[1][1:,1:] # yuqoridan 13, 14, 16, 17 Ni ajratib olish
print(sliced_arr3d)

[[13 14]
 [16 17]]


In [ ]:
# 2 qism Math functions
import numpy as np
arr15 = np.random.randn(5,4)
arr15

array([[-0.48536355,  0.08187414,  2.31465857, -1.86726519],
       [ 0.68626019, -1.61271587, -0.47193187,  1.0889506 ],
       [ 0.06428002, -1.07774478, -0.71530371,  0.67959775],
       [-0.73036663,  0.21645859,  0.04557184, -0.65160035],
       [ 2.14394409,  0.63391902, -2.02514259,  0.18645431]])

In [ ]:
arr15.sum()

np.float64(-1.4954654132393692)

In [ ]:
np.sum(arr15)

np.float64(-1.4954654132393692)

In [ ]:
arr15.sum(axis=1)  # ustun yig'indisi

array([ 0.04390397, -0.30943695, -1.04917072, -1.11993655,  0.93917484])

In [ ]:
arr15.sum(axis=0)  # qator yig'indisi

array([ 1.67875412, -1.7582089 , -0.85214776, -0.56386288])

In [ ]:
# mean
mean = np.sum(data)/len(data)
print(mean)

3.3333333333333335


In [ ]:
np.mean(data)

np.float64(3.3333333333333335)

In [ ]:
arr15

array([[-0.48536355,  0.08187414,  2.31465857, -1.86726519],
       [ 0.68626019, -1.61271587, -0.47193187,  1.0889506 ],
       [ 0.06428002, -1.07774478, -0.71530371,  0.67959775],
       [-0.73036663,  0.21645859,  0.04557184, -0.65160035],
       [ 2.14394409,  0.63391902, -2.02514259,  0.18645431]])

In [ ]:
np.mean(arr15, axis=1) # ustun bo'yicha yig'indisi

array([ 0.01097599, -0.07735924, -0.26229268, -0.27998414,  0.23479371])

In [ ]:
np.mean(arr15, axis=0) # qator bo'yicha yig'indisi

array([ 0.33575082, -0.35164178, -0.17042955, -0.11277258])

In [ ]:
# cumsum methodi    o'zidan oldin kelgan barcha sonlarni qoshib boradi

data1 = np.arange(1,11,1)
print(data1)
print(f"O'zidan kelgan sonlar yig'indilari: {data1.cumsum()}")

[ 1  2  3  4  5  6  7  8  9 10]
O'zidan kelgan sonlar yig'indilari: [ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
#cumprod methodi              o'zidan oldin kelgan sonlarni ko'paytirib boradi
data2 = np.array([1,2,3,4,5])
print(data2)
print(f"O'zidan oldin kelgan sonlarni ko'paytirib boradi: {data2.cumprod()}")


[1 2 3 4 5]
O'zidan oldin kelgan sonlarni ko'paytirib boradi: [  1   2   6  24 120]


In [ ]:
#calculation the covariance
# hisoblash kerak

In [5]:
# Boolean Indekslash
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names



<class 'numpy.ndarray'>


In [6]:
data = np.random.randn(7,4)
data

array([[-1.18507769, -0.42627425,  0.92845419, -0.59586996],
       [ 2.7905173 , -0.38048476, -0.41575415, -1.3987766 ],
       [-0.14035959, -0.96627576,  1.50360201,  0.68070943],
       [-0.32984946,  0.25076318,  0.51140599,  0.25007229],
       [ 0.66764718, -2.39180373, -0.46088689, -0.65666987],
       [ 0.09613989,  0.12814376,  0.89957444, -0.68502251],
       [-0.22409121,  1.20975606, -0.10701351,  2.59834284]])

In [7]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [8]:
data[names=='Hasan']  # Hasanga tegishli malumotlarni ajratib oladi

array([[-1.18507769, -0.42627425,  0.92845419, -0.59586996],
       [ 0.66764718, -2.39180373, -0.46088689, -0.65666987]])

In [9]:
data[names=='Elyor']  # Elyorga tegishli malumotlarni ajratib oladi

array([[-0.32984946,  0.25076318,  0.51140599,  0.25007229],
       [-0.22409121,  1.20975606, -0.10701351,  2.59834284]])

In [11]:
data[names=='Hasan',2:]    # Hasanga tegishli ohirgi ikkita ustundagi malumotlarni ajratib oladi

array([[ 0.92845419, -0.59586996],
       [-0.46088689, -0.65666987]])

In [12]:
data[names!='Hasan']    # (!=) Hasandan tashqari barcha insonlarning malumotlarini ajratib oladi

array([[ 2.7905173 , -0.38048476, -0.41575415, -1.3987766 ],
       [-0.14035959, -0.96627576,  1.50360201,  0.68070943],
       [-0.32984946,  0.25076318,  0.51140599,  0.25007229],
       [ 0.09613989,  0.12814376,  0.89957444, -0.68502251],
       [-0.22409121,  1.20975606, -0.10701351,  2.59834284]])

In [13]:
data[~(names=='Hasan')]   # (~) yuqoridagi cell bilan bir natija beradi

array([[ 2.7905173 , -0.38048476, -0.41575415, -1.3987766 ],
       [-0.14035959, -0.96627576,  1.50360201,  0.68070943],
       [-0.32984946,  0.25076318,  0.51140599,  0.25007229],
       [ 0.09613989,  0.12814376,  0.89957444, -0.68502251],
       [-0.22409121,  1.20975606, -0.10701351,  2.59834284]])

In [14]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[-1.18507769 -0.42627425  0.92845419 -0.59586996]
 [ 2.7905173  -0.38048476 -0.41575415 -1.3987766 ]
 [-0.14035959 -0.96627576  1.50360201  0.68070943]
 [-0.32984946  0.25076318  0.51140599  0.25007229]
 [ 0.66764718 -2.39180373 -0.46088689 -0.65666987]
 [ 0.09613989  0.12814376  0.89957444 -0.68502251]
 [-0.22409121  1.20975606 -0.10701351  2.59834284]]


In [16]:
mask = (names=='Hasan') | (names=='Husan')    # yoki " | " o'rniga "or" ni ishlatsa ham bo'ladi
mask

array([ True,  True, False, False,  True, False, False])

In [17]:
data[mask,::2]

array([[-1.18507769,  0.92845419],
       [ 2.7905173 , -0.41575415],
       [ 0.66764718, -0.46088689]])

In [18]:
data[mask]   # Hasan va Husanga tegishli malumotlarni ajratib oladi

array([[-1.18507769, -0.42627425,  0.92845419, -0.59586996],
       [ 2.7905173 , -0.38048476, -0.41575415, -1.3987766 ],
       [ 0.66764718, -2.39180373, -0.46088689, -0.65666987]])

In [19]:
data

array([[-1.18507769, -0.42627425,  0.92845419, -0.59586996],
       [ 2.7905173 , -0.38048476, -0.41575415, -1.3987766 ],
       [-0.14035959, -0.96627576,  1.50360201,  0.68070943],
       [-0.32984946,  0.25076318,  0.51140599,  0.25007229],
       [ 0.66764718, -2.39180373, -0.46088689, -0.65666987],
       [ 0.09613989,  0.12814376,  0.89957444, -0.68502251],
       [-0.22409121,  1.20975606, -0.10701351,  2.59834284]])

In [20]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.92845419, 0.        ],
       [2.7905173 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.50360201, 0.68070943],
       [0.        , 0.25076318, 0.51140599, 0.25007229],
       [0.66764718, 0.        , 0.        , 0.        ],
       [0.09613989, 0.12814376, 0.89957444, 0.        ],
       [0.        , 1.20975606, 0.        , 2.59834284]])

In [22]:
# Logical Set

In [21]:
# Massivlar
xarr = np.array([1.1,1.2,1.3,1.4,1.5]) #xarr
yarr = np.array([2.1,2.2,2.3,2.4,2.5]) #yarr

In [23]:
cond = np.array([True, False, True, True, False])

In [24]:
result = np.where(cond, xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [25]:
arr = np.random.randn(4,4)
arr

array([[ 2.18510303, -0.46067825, -1.21513254,  3.0965672 ],
       [-0.70061019,  0.487956  , -0.63359639, -0.26956121],
       [ 2.11186797, -0.51884421,  0.61457776,  0.62312743],
       [ 0.5175342 ,  0.55660782,  0.67270665, -0.46137024]])

In [32]:
results = np.where(arr<0, -2, 2)  # bu yerda (arr<0, -2, 2) degani agar datadagi malumotlar manfiy bolsa -2 musbat bolsa 2 ni qaytaradi
results

array([[ 2, -2, -2,  2],
       [-2,  2, -2, -2],
       [ 2, -2,  2,  2],
       [ 2,  2,  2, -2]])