In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr[2])

3


In [5]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [6]:
arr2.shape

(3, 3)

In [7]:
arr2.ndim

2

In [8]:
arr2.size

9

In [29]:
arr2 + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [9]:
arr1 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]
    ])

In [10]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
zero = np.zeros([3,4,5])

In [44]:
zero

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [12]:
one = np.ones_like([2,3])

In [13]:
one

array([1, 1])

In [14]:
wanted = np.full([3,4],5)

In [15]:
wanted

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
space = np.arange(0,10,2)

In [17]:
space

array([0, 2, 4, 6, 8])

In [18]:
lspace = np.linspace(0, 10, 8)

In [19]:
lspace

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [20]:
wanted.dtype

dtype('int64')

In [21]:
wanted.itemsize

8

In [22]:
wanted = wanted.astype('float64')

In [23]:
wanted

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
print(wanted[1:3,0:2])

[[5. 5.]
 [5. 5.]]


In [27]:
arr4 = np.array([1,2,3,4,5,6,7,8,9])

In [29]:
print(arr4[::3])

[1 4 7]


In [33]:
print(arr2[:,0:2])

[[1 2]
 [4 5]
 [7 8]]


In [34]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
print(arr2[1:3,1:2])

[[5]
 [8]]


In [37]:
print(arr2[arr2>=3])

[3 4 5 6 7 8 9]


In [39]:
l1 =[1,2,3,4,5]
l2 =[6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

In [42]:
print(l1+l2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [43]:
print(a1+a2)

[ 7  9 11 13 15]


In [45]:
print(a1+5)

[ 6  7  8  9 10]


In [47]:
dot = np.dot(a1,a2)
dot

np.int64(130)

In [48]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
a1@a2

np.int64(130)

In [ ]:
#sum, min, max, mean, mean

In [55]:
m1 = np.median(arr2)
m2 = np.sum(arr2)
m3 = np.square(arr2)
m3

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [57]:
arr5 = np.array([1,2,3,4,5,6,7,8,9])

In [59]:
arr6 = arr5.reshape(3,3)
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
new_arr6 = np.resize(arr6,(2,3))
new_arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr7 = arr6.copy()
arr7.resize(3,5,refcheck=False)
arr7

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [75]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9]])
arr3 = np.concatenate((arr1,arr2),axis=0)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr9 = np.split(arr5,3)
arr9

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([[10,11,12]])

In [89]:
b = np.random.rand(2,3,4)
b

array([[[0.21110216, 0.39469454, 0.55516956, 0.58729022],
        [0.40691281, 0.71194687, 0.146216  , 0.70115354],
        [0.58464904, 0.07760698, 0.04080649, 0.9480715 ]],

       [[0.72257375, 0.91004222, 0.94021203, 0.01845067],
        [0.24940971, 0.88204715, 0.33488695, 0.8717653 ],
        [0.00963206, 0.33849553, 0.78528276, 0.0919695 ]]])

In [112]:
c = np.random.randint(1,50, size=(3,3))
c

array([[10, 33, 17],
       [39, 44, 41],
       [ 6, 44,  3]])

In [140]:
list = [10,20,30,40,50,60,70,80]
choice = np.random.choice(list, size = (3,2), replace = True)
choice

array([[60, 70],
       [60, 30],
       [40, 70]])

In [133]:
np.random.seed(42)
r = np.random.rand(3)
r

array([0.37454012, 0.95071431, 0.73199394])

In [143]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.random.shuffle(arr)
arr

array([ 3,  8,  5,  1,  7,  2,  6, 10,  9,  4])