In [ ]:
import numpy as np

# Tezlikdagi farq
my_list = list(range(10000))
my_array = np.array(range(10000))
my_list
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
 %%time
 for _ in range(1000): [x*2 for x in my_list] # normal

CPU times: user 364 ms, sys: 967 µs, total: 365 ms
Wall time: 368 ms


In [ ]:
%%time
for _ in range(1000): my_array * 2 # numpy

CPU times: user 12.3 ms, sys: 0 ns, total: 12.3 ms
Wall time: 25.5 ms


In [ ]:
l1 = [1, 2, 3, 5]
l1*2 # for list

[1, 2, 3, 5, 1, 2, 3, 5]

In [ ]:
arr = np.array(l1)
arr*2 # for array numpy

array([ 2,  4,  6, 10])

Making array

In [ ]:
# data yaratish
data = [3.5, 5, 6, 2] # list
arr1 = np.array(data)
arr1

array([3.5, 5. , 6. , 2. ])

In [ ]:
data

[3.5, 5, 6, 2]

In [ ]:
arr1

array([3.5, 5. , 6. , 2. ])

In [ ]:
data2 = (1, 4, 6, 10)# tuple
arr2 = np.array(data2)
arr2

array([ 1,  4,  6, 10])

Massiv o'lchami (ndim)

In [ ]:
arr2.ndim

1

In [ ]:
data3 = [[1, 2, 4, 5], [6, 5, 7, 10]]
arr3 = np.array(data3)
arr3

array([[ 1,  2,  4,  5],
       [ 6,  5,  7, 10]])

In [ ]:
arr3.ndim

2

Shape bu arrayni o'lchamini beradi

Size arrayni nechta elementi bolrigini beradi

In [ ]:
arr2.shape

(4,)

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr2.size

4

In [ ]:
arr3.size

8

N o'lchamli massivlar yaratishning boshqa usullari

In [ ]:
arr4 = np.zeros((2,4)) # 2x4 o'lchamli barcha elementlari 0 dan iborat array
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((2, 4)) # 2x4 o'lchamli barcha elementlari 1 dan iborat array
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr6 = np.arange(2, 20, 4)
arr6

array([ 2,  6, 10, 14, 18])

In [ ]:
np.random.seed(42) # randomni fix qilib qo'yish uchun
arr7 = np.random.rand(2, 4)
arr7

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [ ]:
 # nornal distribution sampling
 arr7 = np.random.randn(2,4)
 arr7

array([[-1.32818605,  0.19686124,  0.73846658,  0.17136828],
       [-0.11564828, -0.3011037 , -1.47852199, -0.71984421]])

In [ ]:
arr8 = np.random.randint(2, 5, size=(2,4))
arr8

array([[4, 2, 3, 4],
       [3, 2, 4, 2]])

In [ ]:
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr9 = np.array([1, 2, 3], dtype=np.int32)
arr9 # accuracy qanchalik katta bo'lsa shunchalik katta xotira kerak

array([1, 2, 3], dtype=int32)

In [ ]:
arr9.itemsize # bir dona raqat hajmi

4

In [ ]:
arr9.nbytes # umumiy hajmini beradi

12

In [ ]:
arr10 =np.random.randn(2, 5)
arr10

array([[-2.65517605,  0.34551794, -0.39551645, -0.28913686,  0.45293633],
       [-0.16606091,  0.21493883, -2.02231493, -0.94305681,  1.40395874]])

In [ ]:
arr10.astype(np.int64) # datatypeni int64 ga o'zgartirish

array([[-2,  0,  0,  0,  0],
       [ 0,  0, -2,  0,  1]])

In [ ]:
arr10.dtype

dtype('float64')

Indeks

Array mutable !


In [ ]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[3:5] # slicing

array([40, 50])

In [ ]:
sliced_arr = arr[3:5]
sliced_arr

array([40, 50])

In [ ]:
copied_arr = arr.copy
arr[-1] = 99
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 99])

2D array indeks va kesib olish

In [ ]:
arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
sliced_arr2d = arr2d[1:, 1:]
sliced_arr2d

array([[4, 5],
       [7, 8]])

In [ ]:
arr2d[1:, ::2]

array([[3, 5],
       [6, 8]])

3D array


In [ ]:
arr3d=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[11,22,33],
                 [44,55,66],
                 [77,88,99]],
                [[10,20,30],
                 [40,50,60],
                 [70,80,90]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [ ]:
arr3d[0][2,2]

np.int64(9)

In [ ]:
arr3d[1,1:, 1:]

array([[55, 66],
       [88, 99]])

Math Statistics