In [1]:
import numpy as np

In [2]:
# Bizda ismlar bor
names = np.array(['Hasan', 'Husan', 'ELyor', 'Mirzabek', 'Otabek', 'Husan', 'Mirzabek'])
names

array(['Hasan', 'Husan', 'ELyor', 'Mirzabek', 'Otabek', 'Husan',
       'Mirzabek'], dtype='<U8')

In [4]:
# data yaratamiz yana
data = np.random.randn(7,4)
data

array([[-0.01288351, -0.55145099,  0.59429404,  2.21329898],
       [ 0.39524672,  0.11786722, -0.83606267,  1.39313626],
       [-0.25650813, -0.34725679, -0.19558459, -0.76720152],
       [-1.80412463,  0.76109367, -0.42887219, -1.32169543],
       [ 1.20357605, -0.0821742 , -0.11778223,  0.60334257],
       [-0.43307244, -0.86749706,  2.69530982,  0.54205523],
       [ 0.78891019, -1.00479721,  2.00425291, -0.62008378]])

In [5]:
names == 'Husan'

array([False,  True, False, False, False,  True, False])

In [6]:
data [names == 'Husan'] # Husanga tegishli barcha ma'lumotlarni ajratib olish

array([[ 0.39524672,  0.11786722, -0.83606267,  1.39313626],
       [-0.43307244, -0.86749706,  2.69530982,  0.54205523]])

In [7]:
data [names == 'Mirzabek'] # Mirzabekka tegishli barcha barcha ma'lumotlarni ajratib olish

array([[-1.80412463,  0.76109367, -0.42887219, -1.32169543],
       [ 0.78891019, -1.00479721,  2.00425291, -0.62008378]])

In [8]:
data [names == 'Husan', 2:] # Husanga tegishli oxirgi ikki ustundagi ma'lumotlarni ajratib olish

array([[-0.83606267,  1.39313626],
       [ 2.69530982,  0.54205523]])

In [9]:
data [names != 'Husan'] # Husandan tashqari qolganlarni ma'lumotlarini ajratib olish

array([[-0.01288351, -0.55145099,  0.59429404,  2.21329898],
       [-0.25650813, -0.34725679, -0.19558459, -0.76720152],
       [-1.80412463,  0.76109367, -0.42887219, -1.32169543],
       [ 1.20357605, -0.0821742 , -0.11778223,  0.60334257],
       [ 0.78891019, -1.00479721,  2.00425291, -0.62008378]])

In [10]:
data [~(names == 'Husan')] # Bu ham tepadagi bilan bir xil 

array([[-0.01288351, -0.55145099,  0.59429404,  2.21329898],
       [-0.25650813, -0.34725679, -0.19558459, -0.76720152],
       [-1.80412463,  0.76109367, -0.42887219, -1.32169543],
       [ 1.20357605, -0.0821742 , -0.11778223,  0.60334257],
       [ 0.78891019, -1.00479721,  2.00425291, -0.62008378]])

In [11]:
print (names)
print (data)

['Hasan' 'Husan' 'ELyor' 'Mirzabek' 'Otabek' 'Husan' 'Mirzabek']
[[-0.01288351 -0.55145099  0.59429404  2.21329898]
 [ 0.39524672  0.11786722 -0.83606267  1.39313626]
 [-0.25650813 -0.34725679 -0.19558459 -0.76720152]
 [-1.80412463  0.76109367 -0.42887219 -1.32169543]
 [ 1.20357605 -0.0821742  -0.11778223  0.60334257]
 [-0.43307244 -0.86749706  2.69530982  0.54205523]
 [ 0.78891019 -1.00479721  2.00425291 -0.62008378]]


In [12]:
mask = (names == 'Hasa') | (names == 'Husan')
mask

array([False,  True, False, False, False,  True, False])

In [13]:
data[mask]

array([[ 0.39524672,  0.11786722, -0.83606267,  1.39313626],
       [-0.43307244, -0.86749706,  2.69530982,  0.54205523]])

In [15]:
data[mask, :2]

array([[ 0.39524672,  0.11786722],
       [-0.43307244, -0.86749706]])

In [16]:
data

array([[-0.01288351, -0.55145099,  0.59429404,  2.21329898],
       [ 0.39524672,  0.11786722, -0.83606267,  1.39313626],
       [-0.25650813, -0.34725679, -0.19558459, -0.76720152],
       [-1.80412463,  0.76109367, -0.42887219, -1.32169543],
       [ 1.20357605, -0.0821742 , -0.11778223,  0.60334257],
       [-0.43307244, -0.86749706,  2.69530982,  0.54205523],
       [ 0.78891019, -1.00479721,  2.00425291, -0.62008378]])

In [17]:
data[data<0]=0
data

array([[0.        , 0.        , 0.59429404, 2.21329898],
       [0.39524672, 0.11786722, 0.        , 1.39313626],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.76109367, 0.        , 0.        ],
       [1.20357605, 0.        , 0.        , 0.60334257],
       [0.        , 0.        , 2.69530982, 0.54205523],
       [0.78891019, 0.        , 2.00425291, 0.        ]])