In [1]:
import numpy as np

In [15]:
# Indexing va kesib olish asoslari
arr = np.arange(10,100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
arr[3:5]

array([40, 50])

In [17]:
sliced_arr = arr[3:5]
sliced_arr[0] = sliced_arr[0]*2
sliced_arr

array([80, 50])

In [18]:
arr1 = np.arange(4)
arr1

array([0, 1, 2, 3])

In [20]:
arr1 = np.arange(4)
arr1[2] = 5
arr1

array([0, 1, 5, 3])

In [21]:
arr

array([10, 20, 30, 80, 50, 60, 70, 80, 90])

In [22]:
sliced_arr = arr[3:5]
sliced_arr[0] = sliced_arr[0]//2
sliced_arr

array([40, 50])

In [23]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
# Copy usuli haqida
arr [1] = 3
arr

array([10,  3, 30, 40, 50, 60, 70, 80, 90])

In [25]:
# Copy usuli haqida
arr [1] = 20
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
new_array = arr.copy()
new_array 

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
new_array = arr.copy()
new_array [1] = 21
new_array

array([10, 21, 30, 40, 50, 60, 70, 80, 90])

In [28]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
# Keyingisi 2d o'lchamli massivelardan index va kesib olish
arr2d = np.arange(9).reshape(3, 3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr2d[1,2]

np.int64(5)

In [37]:
arr2d[1,1:3]

array([4, 5])

In [41]:
arr2d[1:,1:]

array([[4, 5],
       [7, 8]])

In [45]:
arr2d[1:, 0:: 2]

array([[3, 5],
       [6, 8]])

In [48]:
# Biz endi 3d Arrayga o'tamiz va ustida amallar bajaramiz, qani fighting
# 3D array
arr3d = np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                   
                  [[9,10,11],
                   [12,13,14],
                   [15,16,17]],
                  
                   [[18,19,20],
                   [21,22,23],
                   [24,25,26]]])
arr3d
                      

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [49]:
arr3d [0]  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr3d [0] [2,2]

np.int64(9)

In [51]:
arr3d [1] [1:, 1:]

array([[13, 14],
       [16, 17]])

In [52]:
arr3d [1, 1:, 1:]

array([[13, 14],
       [16, 17]])

In [53]:
arr3d[1:3]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
arr3d[1:3][0:, 1:, :2]

array([[[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])