In [11]:
import numpy as np

In [20]:
my_list = list(range(10000))
my_array = np.arange(10000)
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [23]:
%%time
for _ in range(100):[x*2 for x in my_list]

CPU times: user 32.6 ms, sys: 3.45 ms, total: 36 ms
Wall time: 45.2 ms


In [24]:
%%time
for _ in range(100) : my_array*2

CPU times: user 3.05 ms, sys: 1.64 ms, total: 4.7 ms
Wall time: 4.26 ms


In [25]:
l1 = [1,2,3]
l1*2

[1, 2, 3, 1, 2, 3]

In [27]:
arr1 = np.array(l1)
arr1*2

array([2, 4, 6])

In [33]:
# data yaratamiz
data = [3.7,10,3,6, "Tekshirayotganingiz uchun rahmat!"]
arr2 = np.array(data)
arr2

array(['3.7', '10', '3', '6', 'Tekshirayotganingiz uchun rahmat!'],
      dtype='<U33')

In [34]:
data

[3.7, 10, 3, 6, 'Tekshirayotganingiz uchun rahmat!']

In [35]:
arr2

array(['3.7', '10', '3', '6', 'Tekshirayotganingiz uchun rahmat!'],
      dtype='<U33')

In [36]:
# Keyingi data2ni tuple orqali yaratamiz
data2 = [4,5,3.2,7]
arr3 = np.array(data2)

In [37]:
arr3

array([4. , 5. , 3.2, 7. ])

In [38]:
# Keyingi o'raganadigan narsamiz "Massive o'lchami (ndim)"
arr2

array(['3.7', '10', '3', '6', 'Tekshirayotganingiz uchun rahmat!'],
      dtype='<U33')

In [39]:
arr2.ndim

1

In [40]:
# Ana endi ikki va undan katta o'lchamili arraylar haqida o'rganamiz
data3 = [[1,2,3,4], [5,6,7,8]]
arr4 = np.array(data3)

In [41]:
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
# Buni ham o'lchamini tekshiranmiz
arr4.ndim

2

In [43]:
# Va keyingisi Shape va size atributlari haqida code yozamiz va o'rganamiz
arr3

array([4. , 5. , 3.2, 7. ])

In [44]:
arr3.shape

(4,)

In [45]:
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Bu yerda o'lchamlar 1dan oshsa, o'qishni qatordan boshlaymiz va shuning uchun 2,4 bo'lyapti
arr4.shape

(2, 4)

In [47]:
# Keyingisi endi sizeni ko'rsataman hozir
# Size bu ichida nechta elementi borligi aytadi
arr3.size

4

In [48]:
arr4.size

8

In [50]:
# zero va ones funksiyalari yordamida massivlar yaratish
arr5 = np.zeros((2,4)) # Hozir barcha elementlarni 0 ga aylantiradi
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
arr6 = np.ones ((2,4)) # Elementlar hammasi 1ga aylanadi
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
# Keyingisi "arange" 
arr7 = np.arange(4,20,2) #Python indexda oxirgisi kirmaydi ya'ni 20
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
# random
arr8 = np.random.rand(2,4) 
arr8 #qiymatlari har xil chiqadi, o'zgarib turadi

array([[0.45606998, 0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485, 0.17052412]])

In [61]:
# keyingisi randomni aniq qiymatda ya'ni har safar bir hil qiymatda chiqadigan qilamiz
##np.random.seed(42)
##arr8 = np.random.rand(2,4) 
##arr8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [65]:
# Normal distrubition sampling
arr8 = np.random.randn(2,4)
arr8

array([[-0.60063869, -0.29169375, -0.60170661,  1.85227818],
       [-0.01349722, -1.05771093,  0.82254491, -1.22084365]])

In [68]:
arr9 = np.random.randint(5, size = (2,4))
arr9

array([[1, 1, 3, 4],
       [1, 1, 3, 1]])

In [69]:
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
arr10 = np.array([1,2,3], dtype=np.int8)
arr10

array([1, 2, 3], dtype=int8)

In [71]:
# bu bitta element uchun
arr10.itemsize

1

In [72]:
# Umumiy byteni aniqlab beradi
arr10.nbytes

3

In [73]:
arr8.dtype

dtype('float64')

In [74]:
arr8

array([[-0.60063869, -0.29169375, -0.60170661,  1.85227818],
       [-0.01349722, -1.05771093,  0.82254491, -1.22084365]])

In [75]:
arr8[0,1] = 2
arr8

array([[-0.60063869,  2.        , -0.60170661,  1.85227818],
       [-0.01349722, -1.05771093,  0.82254491, -1.22084365]])

In [76]:
arr8.dtype

dtype('float64')

In [77]:
arr9

array([[1, 1, 3, 4],
       [1, 1, 3, 1]])

In [79]:
arr9[0,2] = 0.1
arr9

array([[1, 1, 0, 4],
       [1, 1, 3, 1]])

In [81]:
    # Bir turdagi ma'lunotlarni boshqasiga o'girish
arr11 = np.random.randn(2, 5)
arr11

array([[ 0.69839894, -0.17162884, -0.90718658,  1.18862573,  0.78553212],
       [ 2.65601009,  0.26348604,  1.64177112,  0.4608163 ,  0.08592347]])

In [83]:
arr11.astype (np.int64)

array([[0, 0, 0, 1, 0],
       [2, 0, 1, 0, 0]])