In [1]:
import numpy as np

In [3]:
# Massivlar
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [4]:
# Shart  
cond = np.array([True,False,False,True,True])

In [5]:
# where
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 2.3, 1.4, 1.5])

In [6]:
arr = np.random.randn(4,4)
arr

array([[-2.25017501,  0.30281024, -0.69856594, -1.16414702],
       [-1.05052438,  0.76763076, -1.13257536, -0.79224922],
       [ 1.27917471,  0.71836091, -0.63019163,  0.64072223],
       [ 0.18858728, -1.14049303,  0.2125744 ,  0.91327725]])

In [7]:
results = np.where(arr<0, -2, 2 ) 
results

array([[-2,  2, -2, -2],
       [-2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [ 2, -2,  2,  2]])