In [4]:
import numpy as np

In [4]:
# Biz navbatdagi data yaratamiz
arr = np.random.randn( 5, 4 ) # 5ga 4 o'lchamili massive
arr

array([[ 0.0532209 ,  1.33427935, -0.9042903 , -0.23007861],
       [-0.72148682,  0.47691116,  0.42541911,  0.14183575],
       [-2.46450678, -0.09216417,  1.18411423, -0.3319278 ],
       [ 0.49807298,  0.26759024,  0.65992785,  0.8103035 ],
       [ 0.64239392,  0.18374508, -0.33627981, -0.65384557]])

In [5]:
arr.sum() # Sum barcha qiymatlar yeg'indisini hisobalab beradi

np.float64(0.9432341954213058)

In [6]:
np.sum(arr)

np.float64(0.9432341954213058)

In [7]:
arr.sum(axis=1) # Bu bizda Axis1 qatoridagi qiymatlar yeg'indisini ko'rsatadi

array([ 0.25313134,  0.32267919, -1.70448452,  2.23589456, -0.16398638])

In [8]:
arr.sum(axis=0) # Bu endi ustun yeg'indisi

array([-1.9923058 ,  2.17036164,  1.02889109, -0.26371273])

In [9]:
# Mean
# Sodda ma'lumotlar
data = np.arange(5) 
data

array([0, 1, 2, 3, 4])

In [10]:
mean = np.sum(data)/len(data) # Bu qo'lda formulani yozib hisoblash
mean

np.float64(2.0)

In [11]:
# Numpy mean shumchaki shu meanni chaqirish o'zi kifoya ham bo'ladi
np.mean(data)


np.float64(2.0)

In [12]:
arr

array([[ 0.0532209 ,  1.33427935, -0.9042903 , -0.23007861],
       [-0.72148682,  0.47691116,  0.42541911,  0.14183575],
       [-2.46450678, -0.09216417,  1.18411423, -0.3319278 ],
       [ 0.49807298,  0.26759024,  0.65992785,  0.8103035 ],
       [ 0.64239392,  0.18374508, -0.33627981, -0.65384557]])

In [13]:
 np.mean(arr)

np.float64(0.04716170977106529)

In [14]:
np.mean(arr, axis=1)

array([ 0.06328284,  0.0806698 , -0.42612113,  0.55897364, -0.0409966 ])

In [15]:
arr.mean(axis=0)

array([-0.39846116,  0.43407233,  0.20577822, -0.05274255])

In [5]:
data = np.array ([1,2,3,4])
data

array([1, 2, 3, 4])

In [6]:
data.cumsum() # Cumsum o'zidan oldingi barcha qiymatlar yeg'indisi

array([ 1,  3,  6, 10])

In [19]:
data = np.array([1,2,3,4])
data.cumprod() # Bu esa ko'paytma

array([ 1,  2,  6, 24])