In [2]:
#Axror assignment5
import numpy as np

In [8]:
itsalist=list(range(9999))
itsarray=np.arange(9999)

In [4]:
itsalist

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [9]:
itsarray

array([   0,    1,    2, ..., 9996, 9997, 9998], shape=(9999,))

In [15]:
%%time
for _ in range(10000): [x*2 for x in itsalist]

CPU times: user 2.02 s, sys: 176 ms, total: 2.2 s
Wall time: 2.21 s


In [16]:
%%time
for _ in range(10000): itsarray*2

CPU times: user 55.6 ms, sys: 2.67 ms, total: 58.2 ms
Wall time: 58.8 ms


In [20]:
nptime = 0.0588
pytime = 2.1
print('machine spent',pytime/nptime, 'more time in python than numpy')
print('it means numpy is waaay efficient')

machine spent 35.714285714285715 more time in python than numpy
it means numpy is waaay efficient


In [30]:
import random
pylist = [random.randint(1,100) for _ in range(50)]
print(len(pylist))
pylist[:10]

50


[37, 94, 27, 9, 56, 26, 52, 22, 38, 3]

In [28]:
len(pylist*3)


150

In [35]:
myarray = np.random.randint(20,30, size=10)
myarray

array([20, 27, 24, 27, 24, 26, 21, 29, 29, 25])

In [37]:
myarray2 = np.random.rand(5,6)
myarray2

array([[0.61282052, 0.65609462, 0.39064452, 0.07894517, 0.9880397 ,
        0.75836304],
       [0.62275866, 0.6708195 , 0.74382331, 0.18040914, 0.59184367,
        0.46485196],
       [0.26973547, 0.4259965 , 0.67118931, 0.62177639, 0.71983593,
        0.74618495],
       [0.74661906, 0.86270069, 0.85664454, 0.63240402, 0.42050503,
        0.12724128],
       [0.61721383, 0.28321024, 0.2214583 , 0.54367451, 0.04066929,
        0.92369728]])

In [38]:
myarray2.ndim

2

In [39]:
myarray2.size

30

In [40]:
myarray2.shape

(5, 6)

In [41]:
myaray3 = np.zeros((5,7))
myaray3

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [47]:
print('shape', myaray3.shape)
print('size', myaray3.size)
print('ndim', myaray3.ndim)

print('also the array itself below:\n', myaray3)

shape (5, 7)
size 35
ndim 2
also the array itself below:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [48]:
import pandas as pd
df = pd.DataFrame(myaray3)
df

0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [51]:
myarray4 = np.ones((7,7))
myarray4

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [52]:
myarray5 = np.arange(5,25,5)
myarray5

array([ 5, 10, 15, 20])

In [53]:
#random raqamlarni ham doim bir xil output qilishni yoli
#seed orqali
np.random.seed(15)
myarray6 = np.random.rand(10,4)
myarray6

array([[0.8488177 , 0.17889592, 0.05436321, 0.36153845],
       [0.27540093, 0.53000022, 0.30591892, 0.30447436],
       [0.11174128, 0.24989901, 0.9176299 , 0.26414685],
       [0.71777369, 0.86571503, 0.80707948, 0.21055058],
       [0.16724303, 0.04670639, 0.03942231, 0.20023081],
       [0.9985434 , 0.37278698, 0.76051027, 0.47347444],
       [0.50971531, 0.94503842, 0.10944665, 0.46509316],
       [0.14155526, 0.53834876, 0.29899866, 0.53774522],
       [0.66562754, 0.3643288 , 0.62301862, 0.64272489],
       [0.41998182, 0.40324243, 0.39042033, 0.40618952]])

In [54]:
pd.DataFrame(myarray6)

0         1         2         3
0  0.848818  0.178896  0.054363  0.361538
1  0.275401  0.530000  0.305919  0.304474
2  0.111741  0.249899  0.917630  0.264147
3  0.717774  0.865715  0.807079  0.210551
4  0.167243  0.046706  0.039422  0.200231
5  0.998543  0.372787  0.760510  0.473474
6  0.509715  0.945038  0.109447  0.465093
7  0.141555  0.538349  0.298999  0.537745
8  0.665628  0.364329  0.623019  0.642725
9  0.419982  0.403242  0.390420  0.406190

In [58]:
#rand vs randn ni asosiy farqi randn da negative random numberlar ham generate boladi
myarray7 = np.random.randn(5)
print(myarray7)
myarray8 = np.random.rand(5)
print(myarray8)

[ 2.04889876 -0.78260896 -0.2503207  -0.30831446  1.72968803]
[0.52049647 0.68456904 0.4252903  0.60347306 0.82384911]


In [59]:
#integerlar bilan
myarray9 = np.random.randint(40, size=(5,5))
pd.DataFrame(myarray9)

0   1   2   3   4
0  15  16  32  33  34
1  33  28  36  23   8
2  39  10  11  13  34
3  15  21  12   3  27
4  20  20  27   0   4

In [60]:
#eye bilan
pd.DataFrame(np.eye(5))

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [62]:
array2 = np.array([1,2,3])
print(array2.dtype)
print(myarray8.dtype)

int64
float64


In [75]:
array10 = np.array([1,2,3], dtype=np.float32)
print(array10)
print(array10.dtype, array10.nbytes)
new_array = array10.astype(np.float16)
print(new_array.dtype, new_array.nbytes)

[1. 2. 3.]
float32 12
float16 6


In [76]:
array10 = np.array([1,2,3], dtype=np.bool)
print(array10, array10.nbytes)
print(array10.dtype)

[ True  True  True] 3
bool


In [77]:
array10.itemsize

1

In [80]:
myarray5

array([ 5, 10, 15, 20])

In [83]:
myarray5[2:]

array([15, 20])

In [86]:
myarray5[-1:]

array([20])

In [90]:
slicedarray=myarray5[-1:]
slicedarray

array([20])

In [93]:
slicedarray[0]

np.int64(20)

In [94]:
myarray6

array([[0.8488177 , 0.17889592, 0.05436321, 0.36153845],
       [0.27540093, 0.53000022, 0.30591892, 0.30447436],
       [0.11174128, 0.24989901, 0.9176299 , 0.26414685],
       [0.71777369, 0.86571503, 0.80707948, 0.21055058],
       [0.16724303, 0.04670639, 0.03942231, 0.20023081],
       [0.9985434 , 0.37278698, 0.76051027, 0.47347444],
       [0.50971531, 0.94503842, 0.10944665, 0.46509316],
       [0.14155526, 0.53834876, 0.29899866, 0.53774522],
       [0.66562754, 0.3643288 , 0.62301862, 0.64272489],
       [0.41998182, 0.40324243, 0.39042033, 0.40618952]])

In [92]:
myarray6[0]

array([0.8488177 , 0.17889592, 0.05436321, 0.36153845])

In [95]:
myarray6[0]*2

array([1.69763539, 0.35779185, 0.10872643, 0.72307689])

In [96]:
myarray6[0]/2

array([0.42440885, 0.08944796, 0.02718161, 0.18076922])

In [98]:
arrr = np.arange(10)
arrr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arrr[6]=55
arrr

array([ 0,  1,  2,  3,  4,  5, 55,  7,  8,  9])

In [101]:
new_array=arrr.copy()
new_array

array([ 0,  1,  2,  3,  4,  5, 55,  7,  8,  9])

In [115]:
array3d = np.random.rand(3,4,5)
array3d

array([[[0.21912028, 0.26267734, 0.77197004, 0.87405602, 0.99203312],
        [0.70830294, 0.41377373, 0.00144461, 0.93303178, 0.85962703],
        [0.07119029, 0.23701683, 0.73614841, 0.26028285, 0.16771962],
        [0.97468474, 0.39167381, 0.30889318, 0.22940539, 0.06117567]],

       [[0.46852377, 0.02376044, 0.71816179, 0.36863282, 0.5512897 ],
        [0.84997281, 0.53071774, 0.99606673, 0.92199185, 0.54484521],
        [0.69602149, 0.83041891, 0.2196513 , 0.43810492, 0.88428638],
        [0.04987925, 0.53686535, 0.25463122, 0.39834575, 0.23240359]],

       [[0.61229422, 0.82942423, 0.92469084, 0.14886116, 0.91384816],
        [0.77236858, 0.77993011, 0.78049678, 0.27245317, 0.31771766],
        [0.45824473, 0.08300445, 0.51290826, 0.64890599, 0.16246289],
        [0.05767769, 0.87879149, 0.5291243 , 0.28144259, 0.78004478]]])

In [117]:
array3d[1:]

array([[[0.46852377, 0.02376044, 0.71816179, 0.36863282, 0.5512897 ],
        [0.84997281, 0.53071774, 0.99606673, 0.92199185, 0.54484521],
        [0.69602149, 0.83041891, 0.2196513 , 0.43810492, 0.88428638],
        [0.04987925, 0.53686535, 0.25463122, 0.39834575, 0.23240359]],

       [[0.61229422, 0.82942423, 0.92469084, 0.14886116, 0.91384816],
        [0.77236858, 0.77993011, 0.78049678, 0.27245317, 0.31771766],
        [0.45824473, 0.08300445, 0.51290826, 0.64890599, 0.16246289],
        [0.05767769, 0.87879149, 0.5291243 , 0.28144259, 0.78004478]]])

In [118]:
array3d[:1]

array([[[0.21912028, 0.26267734, 0.77197004, 0.87405602, 0.99203312],
        [0.70830294, 0.41377373, 0.00144461, 0.93303178, 0.85962703],
        [0.07119029, 0.23701683, 0.73614841, 0.26028285, 0.16771962],
        [0.97468474, 0.39167381, 0.30889318, 0.22940539, 0.06117567]]])

In [127]:
array3d[1:,2:]

array([[[0.69602149, 0.83041891, 0.2196513 , 0.43810492, 0.88428638],
        [0.04987925, 0.53686535, 0.25463122, 0.39834575, 0.23240359]],

       [[0.45824473, 0.08300445, 0.51290826, 0.64890599, 0.16246289],
        [0.05767769, 0.87879149, 0.5291243 , 0.28144259, 0.78004478]]])

In [131]:
array3d[0]

array([[0.21912028, 0.26267734, 0.77197004, 0.87405602, 0.99203312],
       [0.70830294, 0.41377373, 0.00144461, 0.93303178, 0.85962703],
       [0.07119029, 0.23701683, 0.73614841, 0.26028285, 0.16771962],
       [0.97468474, 0.39167381, 0.30889318, 0.22940539, 0.06117567]])

In [132]:
array3d[0][2,2]

np.float64(0.736148408598335)

In [133]:
newww = array3d[0][2,2].astype(np.float32)

In [137]:
newww

np.float32(0.7361484)

In [139]:
array3d[1,1:,:2]

array([[0.84997281, 0.53071774],
       [0.69602149, 0.83041891],
       [0.04987925, 0.53686535]])

In [168]:
np.random.seed(1)
array1 = np.random.randn(5,3,4)
array1

array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
        [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
        [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071]],

       [[-0.3224172 , -0.38405435,  1.13376944, -1.09989127],
        [-0.17242821, -0.87785842,  0.04221375,  0.58281521],
        [-1.10061918,  1.14472371,  0.90159072,  0.50249434]],

       [[ 0.90085595, -0.68372786, -0.12289023, -0.93576943],
        [-0.26788808,  0.53035547, -0.69166075, -0.39675353],
        [-0.6871727 , -0.84520564, -0.67124613, -0.0126646 ]],

       [[-1.11731035,  0.2344157 ,  1.65980218,  0.74204416],
        [-0.19183555, -0.88762896, -0.74715829,  1.6924546 ],
        [ 0.05080775, -0.63699565,  0.19091548,  2.10025514]],

       [[ 0.12015895,  0.61720311,  0.30017032, -0.35224985],
        [-1.1425182 , -0.34934272, -0.20889423,  0.58662319],
        [ 0.83898341,  0.93110208,  0.28558733,  0.88514116]]])

In [162]:
array1.sum()

np.float64(0.4988600951552459)

In [163]:
array1.sum(axis=1)
#row

array([[ 2.80879209, -3.16266549,  2.67874795, -3.89431623],
       [-1.59546459, -0.11718906,  2.07757391, -0.01458171],
       [-0.05420483, -0.99857803, -1.48579711, -1.34518756],
       [-1.25833815, -1.29020891,  1.10355937,  4.5347539 ],
       [-0.18337583,  1.19896247,  0.37686341,  1.11951451]])

In [ ]:
array1.sum(axis=0)

array([[ 1.20563271, -0.82791982,  2.44267996, -2.71883501],
       [-0.90926241, -3.88601333,  0.13931223,  1.70393258],
       [-0.57896161,  0.34425413,  2.16895534,  1.41508533]])

In [169]:
np.mean(array1)

np.float64(0.008314334919254098)

In [ ]:
np.mean(array1, axis=1)

array([[ 0.93626403, -1.05422183,  0.89291598, -1.29810541],
       [-0.53182153, -0.03906302,  0.69252464, -0.00486057],
       [-0.01806828, -0.33285934, -0.4952657 , -0.44839585],
       [-0.41944605, -0.43006964,  0.36785312,  1.51158463],
       [-0.06112528,  0.39965416,  0.12562114,  0.3731715 ]])

In [171]:
np.mean(array1, axis=0)

array([[ 0.24112654, -0.16558396,  0.48853599, -0.543767  ],
       [-0.18185248, -0.77720267,  0.02786245,  0.34078652],
       [-0.11579232,  0.06885083,  0.43379107,  0.28301707]])

In [181]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:

data1 = data.cumsum()
data1

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [189]:
data2 = data[1:]
data2.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [190]:
namearray = np.array(['ali', 'vali', 'sali', 'ani', 'gani', 'tani', 'sani', 'mani', 'uni', 'qani'])

In [196]:
data=np.random.rand(10,5)
data

array([[0.58135893, 0.97001999, 0.8468288 , 0.23984776, 0.49376971],
       [0.61995572, 0.8289809 , 0.15679139, 0.0185762 , 0.07002214],
       [0.48634511, 0.60632946, 0.56885144, 0.31736241, 0.98861615],
       [0.57974522, 0.38014117, 0.55094822, 0.74533443, 0.66923289],
       [0.26491956, 0.06633483, 0.3700842 , 0.62971751, 0.21017401],
       [0.75275555, 0.06653648, 0.2603151 , 0.80475456, 0.19343428],
       [0.63946088, 0.52467031, 0.92480797, 0.26329677, 0.06596109],
       [0.73506596, 0.77217803, 0.90781585, 0.93197207, 0.01395157],
       [0.23436209, 0.61677836, 0.94901632, 0.95017612, 0.55665319],
       [0.91560635, 0.64156621, 0.39000771, 0.48599067, 0.60431048]])

In [194]:
namearray=='ali'

array([ True, False, False, False, False, False, False, False, False,
       False])

In [199]:
data[namearray=='vali']

array([[0.61995572, 0.8289809 , 0.15679139, 0.0185762 , 0.07002214]])

In [201]:
maska=(namearray=='ali') | (namearray=='qani')|(namearray=='tani')
maska

array([ True, False, False, False, False,  True, False, False, False,
        True])

In [211]:
data[data<0.5]=1
data

array([[0.58135893, 0.97001999, 0.8468288 , 1.        , 1.        ],
       [0.61995572, 0.8289809 , 1.        , 1.        , 1.        ],
       [1.        , 0.60632946, 0.56885144, 1.        , 0.98861615],
       [0.57974522, 1.        , 0.55094822, 0.74533443, 0.66923289],
       [1.        , 1.        , 1.        , 0.62971751, 1.        ],
       [0.75275555, 1.        , 1.        , 0.80475456, 1.        ],
       [0.63946088, 0.52467031, 0.92480797, 1.        , 1.        ],
       [0.73506596, 0.77217803, 0.90781585, 0.93197207, 1.        ],
       [1.        , 0.61677836, 0.94901632, 0.95017612, 0.55665319],
       [0.91560635, 0.64156621, 1.        , 1.        , 0.60431048]])

In [218]:
np.random.seed(0)
data1 = np.random.randn(7)
data2 = np.random.randn(7)
condition = np.random.choice([True, False], size=7)
print(data1, data2, condition, sep='\n')

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842]
[-0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351  0.76103773
  0.12167502]
[False  True False  True False  True False]


In [221]:
new_result = np.where(condition, data1, data2)
new_result

array([-0.15135721,  0.40015721,  0.4105985 ,  2.2408932 ,  1.45427351,
       -0.97727788,  0.12167502])

In [222]:

new_results=np.where(data1>0, -1, 1)
new_results

array([-1, -1, -1, -1, -1,  1, -1])

In [223]:
#Alhamdulillah